Style/GlobalVars:
    Enabled: false
Style/SingleSpaceBeforeFirstArg:
    Enabled: true
Style/CollectionMethods:
    Enabled: true
Style/InlineComment:
    Enabled: true
Style/EndOfLine:
    Enabled: true
Style/Encoding:
    Enabled: true