language: ruby
cache: bundler
before_install: gem install bundler
bundler_args: --without=development gurobi
env: JRUBY_OPTS=--2.0
rvm:
  - jruby-head
script: bundle exec rspec --tag ~gurobi
addons:
  code_climate:
    repo_token: 805451e02a4b10cdf4ac9db17a3783edc8e8dab907bb040ff45877f5fa22b3a3
