language: ruby
cache: bundler
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - curl -L https://packagecloud.io/michaelmior/coinor/gpgkey | sudo apt-key add -
  - echo "deb https://packagecloud.io/michaelmior/coinor/ubuntu/ precise main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y coinor-libcbc-dev coinor-libcbc3 coinor-libcoinutils-dev coinor-libcoinutils3v5 coinor-libosi-dev coinor-libosi1 coinor-libclp-dev coinor-libclp1 coinor-libcgl-dev coinor-libcgl1 libstdc++6
  - gem install bundler
  - mysql -uroot -e 'create database nose;'
  - mysql -uroot -Dnose < spec/support/data/mysql.sql
bundler_args: --without=development
rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.9
  - jruby-9.0.5.0
matrix:
  allow_failures:
    - rvm: jruby-9.0.5.0
script:
  - sed -i '/^--tag/d' .rspec
  - bundle exec rspec
addons:
  services:
    - mysql
  code_climate:
    repo_token: 6bb85eb10136dfdb11e56bf53a9679510ca99c3c0f2495c06d6a3cb9670b9954
